models:
  - name: dim_customers
    description: Latest known customer attributes based on most recent order
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique

      - name: customer_name
        data_tests:
          - not_null

      - name: customer_segment
        data_tests:
          - not_null

  - name: dim_products
    description: Latest known product attributes based on most recent sale
    columns:
      - name: product_id
        data_tests:
          - not_null
          - unique

      - name: product_name
        data_tests:
          - not_null

      - name: product_category
        data_tests:
          - not_null

      - name: product_sub_category
        data_tests:
          - not_null

  - name: dim_locations
    description: Unique physical locations derived from sales data
    columns:
      - name: location_sk
        tests:
          - not_null
          - unique

      - name: country
        tests:
          - not_null

      - name: state
        tests:
          - not_null

      - name: city
        tests:
          - not_null

      - name: postal_code
        description: Postal code, can be null

      - name: region
        tests:
          - not_null
