models:
  - name: dim_customers
    description: Latest known customer attributes based on most recent order
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique

      - name: customer_name
        data_tests:
          - not_null

      - name: customer_segment
        data_tests:
          - not_null

  - name: dim_products
    description: Latest known product attributes based on most recent sale
    columns:
      - name: product_id
        data_tests:
          - not_null
          - unique

      - name: product_name
        data_tests:
          - not_null

      - name: product_category
        data_tests:
          - not_null

      - name: product_sub_category
        data_tests:
          - not_null
